site_name: Modelling for Digital Twins
site_description: Documentation for IoT Modelling and Digital Twin Implementation
site_author: Likhith Kanigolla
site_url: https://modeling-digital-twin.github.io/

# Repository
repo_name: Modelling-Digital-Twins
repo_url: https://github.com/likhithkanigolla/IIITS-Demo

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

# Navigation
nav:
- Home: index.md
- Installation:
  - CAPS Installation Guide: caps_installation_guide.md
  - Eclipse CAPS Integration Guide: eclipse_caps_integration_guide.md
  - CupCarbon Installation Guide: cupcarbon_installation_guide.md
- PythonPDEVS:
  - PythonPDEVS Installation Guide: pythonpdevs_installation_guide.md
  - PythonPDEVS Introduction: pythonpdevs_introduction.md
  - PyDEVS Motion Light System: pydevs_motion_light_system.md
- SAML:
  - SAML (Software Architecture Modeling Language) Guide: saml_(software_architecture_modeling_language)_guide.md
  - SAML for Motion Based Lighting System: saml_for_motion_based_lighting_system.md
  - SAML for Temperature based window control: saml_for_temperature_based_window_control.md
- HWML: hardware_modeling_language_(hwml)_guide.md
- Cup Carbon:
  - Essentials: essentials.md
  - Simulate Motion Based Lighting System in Cup Carbon: simulate_motion_based_lighting_system_in_cup_carbon.md
- Code Examples:
  - Overview: code_examples/index.md
  - Motion Based Lighting: code_examples/motion_based_lighting.md
  - Temperature Window Control: code_examples/temperature_window_control.md
- Research: research.md

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/likhithkanigolla
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/likhithkanigolla/

extra_css:
  - assets/css/extra.css

# Deployment settings
use_directory_urls: true

plugins:
  - search
  - pdf-export:
      combined: true
      combined_output_path: pdf/documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT